# Generated by Django 4.1.3 on 2022-11-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shops', '0002_rename_name_city_city_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='home',
            field=models.CharField(max_length=5),
        ),
    ]
